gnu: 389-ds-base: Fix LegacyVersion issue.
LegacyVersion does not exist anymore in packaging.version 25.0
(https://github.com/pypa/packaging/pull/407). Add a stub to prevent runtime
errors such as:

Traceback (most recent call last):
  File "/gnu/store/jq8iknqq5niwx9vchccbnnw6jdb3x8nq-389-ds-base-2.2.2/sbin/.dscreate-real", line 18, in <module>
    from lib389 import DirSrv
  File "/gnu/store/jq8iknqq5niwx9vchccbnnw6jdb3x8nq-389-ds-base-2.2.2/lib/python3.11/site-packages/lib389/__init__.py", line 54, in <module>
    from lib389._entry import Entry
  File "/gnu/store/jq8iknqq5niwx9vchccbnnw6jdb3x8nq-389-ds-base-2.2.2/lib/python3.11/site-packages/lib389/_entry.py", line 20, in <module>
    from lib389.utils import (ensure_str, ensure_bytes, ensure_list_bytes, display_log_data)
  File "/gnu/store/jq8iknqq5niwx9vchccbnnw6jdb3x8nq-389-ds-base-2.2.2/lib/python3.11/site-packages/lib389/utils.py", line 49, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/gnu/store/5ga1x27pz9wqwhq3sndcymfngdvcr4w9-python-packaging-bootstrap-25.0/lib/python3.11/site-packages/packaging/version.py)

* gnu/packages/patches/389-ds-base-legacy-version.patch: New file.
* gnu/local.mk (dist_patch_DATA): Add it.
* gnu/packages/openldap.scm (389-ds-base): Use it.

Change-Id: I34c12dce3092f9911383ae380af13ef74285ebc4