Revert "gnu: perl-tk: Fix build with gcc-14."
This is beyond hope

    tkGlue.c:5262:46: error: macro "pregcomp" passed 3 arguments, but takes just 2
     5262 |  p->pat = pregcomp(string,string+len,p->flags);
          |                                              ^
    /gnu/store/kpj90nrq7d59xhbk2pfmzyvv5dya0sfr-perl-5.36.0/lib/perl5/5.36.0/x86_64-linux-thread-multi/CORE/embed.h:464:9: note: macro "pregcomp" defined here

This reverts commit a85225586b4669c893efb3b391543ae6a47eb8ea.

Change-Id: Id0de592e39fb5f33e225289e86ac76121e6e6fea